[package]
name = "ising"
version = "0.1.0"
authors = ["Paweł Rubin <prubin@vewd.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rayon = "1.5.0"
console = "0.14.1"
linya = "0.2.0"
